### ISSUE TITLE
Buffer is deprecated error on version 0.9.2

### ISSUE THREAD

**Issue by celia-tray** [DataDog/synthetics-ci-github-action#114]
```
Run DataDog/synthetics-ci-github-action@v0.9.2
(node:1714) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Getting this error when running the tests without any extra variables:
```
      - name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v0.9.2
        with:
          api_key: $DATADOG_API_KEY
          app_key: $DATADOG_APP_KEY
          test_search_query: 'tag:ci-test'
```
