### ISSUE TITLE
polling_timeout does not seem to get picked up by action

### ISSUE THREAD

**Issue by juliensanmartin** [DataDog/synthetics-ci-github-action#150]
Hi,

I am using Datadog synthetics action version `0.12.0` and added `polling_timeout` to my action to increase the timeout from 30 min to 60 min before action fail, in a script like so:

```
name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v0.12.0
        with:
          api_key: ${{secrets.DD_API_KEY}}
          app_key: ${{secrets.DD_APP_KEY}}
          public_ids: 'foo, bar'
          polling_timeout: 3600000
```

However the action still fails after 30 minutes (see example run below)

![Screenshot 2023-05-24 at 4 45 17 PM](https://github.com/DataDog/synthetics-ci-github-action/assets/18599860/354013dc-fe9b-4df5-b79e-856c1db04b35)

did I do something wrong or can it be a bug?
