### ISSUE TITLE
How to use START_URL in workflow?

### ISSUE THREAD

**Issue by MattRey** [DataDog/synthetics-ci-github-action#169]
Have been struggling to get a synthetic triggered with a different start url as described in the docs.

Adding this to my synthetics.yml file triggers the correct test but it only runs on the start url defined in the Synthetic UI, not the one provided in variables:

```
name: Run Synthetic tests using search query
jobs:
  e2e_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v0.15.0
        with:
          api_key: ${{secrets.DD_API_KEY}}
          app_key: ${{secrets.DD_APP_KEY}}
          test_search_query: 'tag:staging'
          variables: 'START_URL=https://mywebsite.com'  // this has no effect
```
I can trigger it via postman using the Datadog api but I'd appreciate a nudge in the right direction with this one 🙏 

Thank you!
