### ISSUE TITLE
Failed Synthetic tests doesn't fail the Github action step

### ISSUE THREAD

**Issue by 29decibel** [DataDog/synthetics-ci-github-action#187]
Config:

```yaml
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v0.18.0
        with:
           api_key: ${{secrets.SYNTHETIC_DD_API_KEY}}
           app_key: ${{secrets.SYNTHETIC_DD_APP_KEY}}
           public_ids: 'xxx-xxx-xxx'
```

Output:
```
View pending summary in Datadog: https://app.datadoghq.com/synthetics/explorer/ci?batchResultId=907abcf1-9843-4002-8001-1b4385ce01ac

- Waiting for 1 test result (jqh-uv5-fqx)…

  Waiting for 1 test result (jqh-uv5-fqx)…


=== REPORT ===
Took 290941ms

✖ [non-blocking] [jqh-uv5-fqx] [Browser] US XYZ staging UI Preview - location: N. California (AWS) - device: chrome.laptop_large
  ⎋ Total duration: 70705 ms - View test run details: https://app.datadoghq.com/synthetics/details/jqh-uv5-fqx/result/1032458531758739575?from_ci=true 
    ✓ | 3422ms - Navigate to start URL
    https://xya.com/xxx
    ✓ | 1309ms - Type text on input #user_password
    {{ USER_PASSWORD }}
    ✓ | 1339ms - Click on input "commit"
    ✓ | 4635ms - Navigate to link
    https://xyz.com/xxxxx
    ✖ | 60000ms - Click on span #ember14555555
    Error: Cannot locate element.

View full summary in Datadog: https://app.datadoghq.com/synthetics/explorer/ci?batchResultId=907abcf1-9843-4002-8001-1b4[38](https://github.com/xyz/xyz-app/actions/runs/6052540194/job/16426220784?pr=53512#step:3:39)5ce01ac

Continuous Testing Summary:
Test Results: 0 passed, 0 failed, 1 failed (non-blocking)
Max parallelization configured: 1 test running at the same time
Total Duration: 4m 51s

Increase your parallelization to reduce your total duration: https://app.datadoghq.com/synthetics/settings/continuous-testing


Datadog Synthetics tests succeeded: criticalErrors: 0, passed: 0, failedNonBlocking: 1, failed: 0, skipped: 0, notFound: 0, timedOut: 0
Results URL: https://app.datadoghq.com/synthetics/explorer/ci?batchResultId=907abcf1-9843-[40](https://github.com/xyz/xyz-app/actions/runs/6052540194/job/16426220784?pr=53512#step:3:41)02-8001-1b[43](https://github.com/xyz/xyz-app/actions/runs/6052540194/job/16426220784?pr=53512#step:3:44)85ce01ac
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Run Datadog Synthetic tests
```

Expected:
Since synthetic tests failed, we would expect it to exit with code 1 so it can fail the GHA.

```
##[debug]Node Action run completed with exit code 1
```
