### ISSUE TITLE
unable to add synthetics-config.json file

### ISSUE THREAD

**Issue by robfarb** [DataDog/synthetics-ci-github-action#218]
I'm attempting to add a `synthetics-config.json` file to overwrite `"failOnTimeout": false`. I followed the example provided in the [Datadog Synthetics CI](https://github.com/marketplace/actions/datadog-synthetics-ci) action.

Here is the code snippet from the `deploy.yml` file which lives in `./.github/workflows/deploy.yml`
```  
e2e_testing:
    name: Datadog Synthetics Tests
    runs-on: ubuntu-latest
    needs: [setup, integration, unit-test, buildNext, buildDesign, buildLegacy]
    steps:
      - name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v0.2.1
        with:
          api_key: ${{secrets.DATADOG_API_KEY}}
          app_key: ${{secrets.DATADOG_APP_KEY}}
          config_path: ./.github/workflows/synthetics-config.json
          public_ids: 'et8-nd3-dmm, yxg-99h-tnv, 4b3-y2u-jk9, reh-i3i-pw5'
```

When the action runs, I keep running into the following error: `Error: Unable to parse config file! Please verify config path : ./.github/datadog-config/synthetics-config.json`

![Screen Shot 2024-01-25 at 11 54 47 AM](https://github.com/DataDog/synthetics-ci-github-action/assets/94400806/d4f956f0-9a21-4e2d-bcb7-7584932d5bc6)

Where am I supposed to place the `synthetics-config.json` file in my repository and how should I reference it from the config_path key in the action description? Thank you!

**Comment by robfarb** [comment]
**Update**
The issue was that the documentation at https://github.com/marketplace/actions/datadog-synthetics-ci is outdated. I updated the code to follow the documentation at https://github.com/DataDog/synthetics-ci-github-action.

```
  e2e_testing:
    name: Datadog Synthetics Tests
    runs-on: ubuntu-latest
    needs: [setup, integration, unit-test, buildNext, buildDesign, buildLegacy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v0.24.0
        with:
          api_key: ${{secrets.DATADOG_API_KEY}}
          app_key: ${{secrets.DATADOG_APP_KEY}}
          config_path: ./.github/workflows/synthetics-config.json
          public_ids: 'et8-nd3-dmm, yxg-99h-tnv, 4b3-y2u-jk9, reh-i3i-pw5'
```


This did the trick!
