### ISSUE TITLE
Error: Missing API or APP keys to initialize datadog-ci with any version of synthetics-ci-github-action

### ISSUE THREAD

**Issue by nive-copia** [DataDog/synthetics-ci-github-action#343]
Hello: 
 
I use DataDog GHA as follows in my Github workflow. The secrets are available in the repo and matches to whats present in our datadog's org's setting

```
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@68775f0d3317fe740c62f14e8c195de35ec74c52 #v3.3.0
        with:
          app-key: ${{ secrets.DD_APPLICATION_KEY }}
          api-key: ${{ secrets.DD_API_KEY }}
          public-ids: "${{ inputs.data-dog-public-ids }}"
```

However, I am running into the following error:

```
Run DataDog/synthetics-ci-github-action@v3.3.0
  with:
    api-key: ***
    public-ids: id-1, id-2
    tunnel: false
Error: Missing API or APP keys to initialize datadog-ci!

/home/runner/work/_actions/DataDog/<GHA Name>/v3.3.0/node_modules/@actions/core/lib/core.js:110
        throw new Error(`Input required and not supplied: ${name}`);
^
Error: Input required and not supplied: app-key
```

We have not run this GHA for sometime now. Previous when we ran it, it was running with v1.14.1 and it was successful and this was the output

````
Run DataDog/synthetics-ci-github-action@v1.14.1
  with:
    api_key: ***
    app_key: ***
    public_ids: id-1(https://github.com/<test-url>), id-2
    tunnel: false
[id-1] Found test "*********"
[id-2] Found test "*********"
````

When I restored to using v1.14.1, it errors as follows:

```
Run DataDog/synthetics-ci-github-action@v1.14.1
  with:
    public_ids: id-1, id-2
    tunnel: false
Error: Missing API or APP keys to initialize datadog-ci!
.....
        throw new Error(`Input required and not supplied: ${name}`);
^
Error: Input required and not supplied: api_key
```
